import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create Stuepp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-no-repeat bg-slate-900 bg-cover '>{children}</body>
    </html>
  );
}

//{inter.className}